po: add Georgian translation
baszoetekouw/pinfo pull request #29
Opened 2022-09-03 20:29 UTC by NorwayFun

po: add Georgian translation

2024-04-10 04:55 UTC, NorwayFun commented
Hello,
Could you merge this one, please?
Trying to get as much packages localized as I could before RHEL10 release.

Thanks in advance.
Temuri

2025-02-16 20:04 UTC, baszoetekouw commented
Sorry for the long wait, merging now!

2025-02-16 20:08 UTC, baszoetekouw requested changes
Sorry, I was quick to comment.  Could you please also add the new language to the `configure.ac` and the `pinfo.spec.in` files (see https://github.com/baszoetekouw/pinfo/pull/37 for an example).

2025-02-16 23:48 UTC, NorwayFun commented
Hello,
Added requested changes, but I think github did something wrong with spec.in file

temuri

2025-02-17 14:23 UTC, baszoetekouw requested changes

2025-02-17 14:23 UTC, baszoetekouw commented on pinfo.spec.in
> +%lang(de) %{_datadir}/locale/ka/LC_MESSAGES/*
This should probably be `%lang(ka)`

2025-06-20 08:18 UTC, closed without merging